### ISSUE TITLE
Bug with repositories / projects that contain submodules (autoroot)

### ISSUE THREAD

**Issue by ghillb** [benwainwright/fzf-project#13]
I came across the following behavior while working with projects/repositories that contain submodules: 

At first, after opening the project via the project switcher, the editor is in the correct root (1.).
When opening a file within a submodule (2.), the plugin re-roots the editor to a directory where
git keeps its technical submodule related files (3.).

**Intended behaviour:** The root should stay at (1.)  
**Tested with:**  `vim 8.2` & `nvim 0.5`  
```
repo root                  (1.)
  ├── .git
  │   ├── branches
  │   ├── hooks
  │   ├── info
  │   ├── logs
  │   ├── modules
  │   │   ├── submodule 1  (3.)
  │   │   └── submodule 2
  │   ├── objects
  │   └── refs
  ├── submodule 1          (2.)
  │   └── files ...
  └── submodule 2
      └── files ...
  ```

Thank you for your great plugin!

**Comment by benwainwright** [comment]
Thanks!

I've not been keeping on top of Github notifications lately so I'd not spotted this issue. I'll have a look at it this week :)

**Comment by benwainwrightcinch** [comment]
Sorry for the delay. I've now changed the rooting mechanism so that it doesn't rely on Git to identify projects; it just compares with the originally generated list. That means submodules are no longer an issue
