### ISSUE TITLE
Error detected while processing function FzfSwitchProject

### ISSUE THREAD

**Issue by mhristof** [benwainwright/fzf-project#2]
Hi,

awesome project.

I've setup my vimrc like this

```
let g:fzfSwitchProjectWorkspaces = [ '~/code']
let g:fzfSwitchProjectAlwaysChooseFile = 0
```

and when i type `FzfSwitchProject` i get the list of projects without any issues.
When i select the project, i get this error

```
Error detected while processing function FzfSwitchProject[4]..fzf#run[67]..function FzfSwitchProject[4]..fzf#run[63]..<SNR>24_callback:
line   21:
Vim:E488: Trailing characters: ():       FzfChooseProjectFile()
Press ENTER or type command to continue
```
and when i press enter, the `pwd` seems to be correct.

Any ideas why im getting the error ?

**Comment by benwainwright** [comment]
Hi there!

If you can provide me with a minimal vimrc (that is - a complete, working vimrc containing ONLY your configuration for this plugin) that replicates the one you describe, I'll have a go at debugging it for you.

**Comment by benwainwright** [comment]
Sorry about that. I'll have a look shortly.

**Comment by benwainwright** [comment]
Hi there!

I've just had a go at reproducing your error and I'm not able to. Are you able to provide me with a minimal `.vimrc` that reproduces the problem? 

What I mean by that is a working `.vimrc` containing JUST your configuration for this plugin and nothing else.

**Comment by mhristof** [comment]
I've created a repo to reproduce the problem

https://github.com/mhristof/20200921_172639

The vimrc is not minimal as im installing `vundle` to install your plugin (which might be the origin of the problem).

**Comment by oscarprabhakar** [comment]
@mhristof use `benwainwright/fzf-project` rather than `benwainwright/fzf-switch-project`
@benwainwright the README needs updating. Thanks for the plugin by the way. Enjoying it!

**Comment by mhristof** [comment]
I can confirm that using `benwainwright/fzf-project` instead of `benwainwright/fzf-switch-project` makes im issue go away

**Comment by benwainwright** [comment]
Whoops! Thanks guys. Will update README when I get a chance.

@oscarprabhakar no problem! It's nice to give rather than receive for a change hahaha

**Comment by benwainwright** [comment]
I've now updated the readme. Whoops!
