### ISSUE TITLE
Support configurable behaviour of closing all opened buffers after switching project

### ISSUE THREAD

**Issue by shaunwen** [benwainwright/fzf-project#20]
# Feature request
This ticket is to request a new feature to support configurable behaviour of closing all opened buffers after switching project.

# Context
I found the plugin does not close opened buffers after switching to a new project, as a result, if users use fzf to search files it does not search files from the new project switched to, instead it will search files from the same folder with whatever buffer initially opened before switching project. 

# Proposed solution
A proposed solution would be wipe out all opened buffers before switching project if any new project is selected from the popup.

**Comment by benwainwright** [comment]
I've merged your suggestion :)
