### ISSUE TITLE
fzf-project should keep the ability to preserve fzf standard behaviour.

### ISSUE THREAD

**Issue by guillaume-tessier-cbp** [benwainwright/fzf-project#3]
I just discovered the project through Reddit and give it a try.
First of all, I think it's a very interesting feature to choose a project directory and narrow searches inside this very project. Thanks 👍  !

However, once a file is opened with `fzf-project`, the next normal use of `fzf` restricts the search to this project (probably because of `cd` to root porject directory). So, I cannot use `fzf` to open files in other directories (root `fzf` as `$HOME`).

Well, maybe I could suggest the user to be able:
- to keep using fzf the standard way (maybe bound to `<c-f>`) 
- open files in selected project with `<c-F>`, for exemple.

**Comment by benwainwright** [comment]
Hey there - thanks for getting in touch!

Just so I understand you better, what do you mean "the next normal use of `fzf`"? Which command are you talking about?

Can you perhaps describe the **exact** behaviour you are referring to, and the one you'd like to achieve? At the present I'm not clear.

**Comment by guillaume-tessier-cbp** [comment]
No problem, I'll try to be clearer.

1- simply install the plugin (not even configuring `fzfSwitchProjectWorkspaces`.
2- I open a file within a Git repo `fzf` `:Files<CR>` ==> `fzf` keeps its search root at `$HOME`
3- I try to open another file with `:Files<CR>` ==> `fzf` search is narrowed to the 'project'.

I know that is the plugin aim to restrict search to project. 

However, I would appreciate that fzf `:Files` or other fzf commands not to be tainted by the plugin.
For exemple, you could define a `:FzfSearchInProject` command that would not override fzf `:Files` (but probably use it internally).
Then users could bind this plugin command to `<c-F>` (fzf is bound to `<c-f>` in my config).

Therefore, users could hit different keys for different purposes : classic fzf search starting from $HOME, or your plugin to search inside project.)

Broadly, the plugin is to invasive on the fzf standard behaviour. I'd prefer this standard behaviour to be kept.

Hope I was a bit clearer.

**Comment by benwainwright** [comment]
Hi @guillaume-tessier-cbp 

This plugin doesn't modify the `fzf` standard behaviour in any way. It simply changes the current working directory, which is a pretty normal thing to do when working with vim. I won't be making this change you suggest I'm afraid unless there is a clamour of requests for it; it would be entirely contrary to the aims of the workflow I'm trying to facilitate. 

My aim is not just to restrict search, rather it is to _facilitate_ search after having changed the working directory. Changing the working directory has more implications than just narrowing down search; it means that `:e` will be relative to the selected project directory, tests run using `vim-test` will now be run there etc.

Also to make the change you suggest, I'd have to entirely rework the way this plugin is implemented.

**However**

I'm willing to explore adding an extra command that would allow a global search, so either

- uses `fzf` to search ALL the files within ALL the project folders specified via the `g:fzfSwitchProjectWorkspaces` and `g:fzfSwitchProjectProjects` variables
- uses `fzf` to search some other set of folders specified in a configuration setting perhaps

**Comment by guillaume-tessier-cbp** [comment]
Yes, I understand.

Indeed, it happens I work with `.gitlab-ci.yml` and related files that are present in many projects. Sometimes, it realize I am editing the wrong one. Your plugin would make it much easier to narrow search to a project. Creating new files whithin the same project is a must (instead of having to dig deep in the filesystem !).

But, lets say I wish to edit my .vimrc file... Then fzf does not find it anymore unless I do some more actions.

This is why I was thinking about your plugin not to taint fzf default behaviour.
Like, having your own command that would use fzf, keep track of project directory chosen but release the current working directory after the action is completed.

**Comment by benwainwright** [comment]
> plugin not to taint fzf default behaviour

Just to repeat myself; it _doesn't_

> but release the current working directory after the action is completed.

That's a hard no I'm afraid. That's entirely contrary to the aims of this project.
