### ISSUE TITLE
nvim 0.5.0+ bug: file chooser has 'i' already inserted after project has been choosen

### ISSUE THREAD

**Issue by ghillb** [benwainwright/fzf-project#8]
Hello,

your plugin is just awesome and a real productivity booster!
I have a minor bug to report, that happens on nvim 0.5.0:
After choosing a project, the file chooser has already an 'i' inserted. 

**setup:**
- ubuntu 20.04
- nvim installed via: `sudo snap install nvim --classical --edge`
- vimrc: minimal setup to get this plugin going from the README

**screenshots:**
nvim 0.5.0:
<img width="445" alt="bug" src="https://user-images.githubusercontent.com/35503959/95664604-cb85e500-0b49-11eb-972e-29b9fa0c4081.png">

nvim 0.4.4:
<img width="445" alt="nobug" src="https://user-images.githubusercontent.com/35503959/95664611-d6d91080-0b49-11eb-97ef-4d6743a764a5.png">

This PR, fixes the issue for me:
https://github.com/benwainwright/fzf-project/pull/7

**Comment by benwainwright** [comment]
Huh. That's interesting. Thanks for the report, I'll have a look at that this evening.

**Comment by benwainwright** [comment]
Oh, you've fixed it 👍
